### PR TITLE
Added chart title for read depth chart

### PR DESCRIPTION
**Pull request by YangQi007**

### CODE REVIEW

**Comment by anderspitman** [comment]
@YangQi007 looking good overall but I noticed there's too much padding at the top

image

**Comment by YangQi007** [comment]
> @YangQi007 looking good overall but I noticed there's too much padding at the top in the case where no label is provided
> 
> image

I didn't consider the case without the label. Do you mean we should create the "div" for the title instead of embedding it in DOM as default?

**Comment by anderspitman** [comment]
You can solve it however you want. I handle this in histogram.js if you want an example of one way to do it.

**Comment by anderspitman** [comment]
Looks good :+1:

**Pull request merged**
